// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.ML;
using FinalFinalcsc415ML.Model;

namespace FinalFinalcsc415ML.Model
{
    public class ConsumeModel
    {
        public static ModelOutput Predict(ModelInput input)
        {

            // Create new MLContext
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine
            string modelPath = @"C:\Users\Luke Albiero\AppData\Local\Temp\MLVSTools\FinalFinalcsc415ML\FinalFinalcsc415ML.Model\MLModel.zip";
            ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

            // Hardcoded example
            input.Quote = "When you finish your Ai homework but Litman wants you to translate the preamble into binary";

            ModelOutput result = predEngine.Predict(input);
            return result;
        }
    }
}
