// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace FinalFinalcsc415ML.Model
{
    public class ModelInput
    {
        [ColumnName("quote"), LoadColumn(0)]
        public string Quote { get; set; }


        [ColumnName("image"), LoadColumn(1)]
        public string Image { get; set; }
    }
}
